import type {Metadata} from 'next'
import {Yanone_Kaffeesatz} from 'next/font/google'
import '@/style/global.scss'

const yanoneKaffeesatz = Yanone_Kaffeesatz({
    weight: '400',
    subsets: ['cyrillic'],
})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}
const RootLayout = ({
    children,
}: Readonly<{
    children: React.ReactNode
}>) => {
    return (
        <html lang="en">
            <body className={`${yanoneKaffeesatz.className}`}>{children}</body>
        </html>
    )
}

export default RootLayout
